In [1]:
## Run the cell below to attempt to programmatically find your crime file
import os,glob

## Getting the home folder from environment variables
home_folder = os.environ['HOME']
# print("- Your Home Folder is: " + home_folder)

## Check for downloads folder
if 'Downloads' in os.listdir(home_folder):
    
    
    # Print the Downloads folder path
    dl_folder = os.path.abspath(os.path.join(home_folder,'Downloads'))
    print(f"- Your Downloads folder is '{dl_folder}/'\n")
    
    ## checking for crime files using glob
    crime_files = sorted(glob.glob(dl_folder+'/**/Crimes_-_2001_to_Present*',recursive=True))
    
    # If more than 
    if len(crime_files)==1:
        RAW_FILE = crime_files[0]
        
    elif len(crime_files)>1:
        print('[i] The following files were found:')
        
        for i, fname in enumerate(crime_files):
            print(f"\tcrime_files[{i}] = '{fname}'")
        print(f'\n- Please fill in the RAW_FILE variable in the code cell below with the correct filepath.')

else:
    print(f'[!] Could not programmatically find your downloads folder.')
    print('- Try using Finder (on Mac) or File Explorer (Windows) to navigate to your Downloads folder.')

- Your Downloads folder is '/Users/Alex/Downloads/'

In [22]:
## (Required) MAKE SURE TO CHANGE THIS VARIABLE TO MATCH YOUR LOCAL FILE NAME
RAW_FILE = "/Users/Alex/Downloads/Crimes_-_2001_to_Present.csv" #(or slice correct index from the crime_files list)

if RAW_FILE == "YOUR FILEPATH HERE":
	raise Exception("You must update the RAW_FILE variable to match your local filepath.")
	
RAW_FILE

'/Users/Alex/Downloads/Crimes_-_2001_to_Present.csv'

In [23]:
## (Optional) SET THE FOLDER FOR FINAL FILES
OUTPUT_FOLDER = 'Data/Chicago/'
os.makedirs(OUTPUT_FOLDER, exist_ok=True)

## Full Workflow

In [24]:
import pandas as pd
pd.set_option('display.max_columns', 100)
pd.set_option('display.float_format',lambda x: f"{x:,.2f}")

In [25]:
chicago_full = pd.read_csv(RAW_FILE)
chicago_full

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,10224738,HY411648,09/05/2015 01:30:00 PM,043XX S WOOD ST,0486,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,False,True,924,9.00,12.00,61.00,08B,"1,165,074.00","1,875,917.00",2015,02/10/2018 03:50:01 PM,41.82,-87.67,"(41.815117282, -87.669999562)"
1,10224739,HY411615,09/04/2015 11:30:00 AM,008XX N CENTRAL AVE,0870,THEFT,POCKET-PICKING,CTA BUS,False,False,1511,15.00,29.00,25.00,06,"1,138,875.00","1,904,869.00",2015,02/10/2018 03:50:01 PM,41.90,-87.77,"(41.895080471, -87.765400451)"
2,11646166,JC213529,09/01/2018 12:01:00 AM,082XX S INGLESIDE AVE,0810,THEFT,OVER $500,RESIDENCE,False,True,631,6.00,8.00,44.00,06,NaN,NaN,2018,04/06/2019 04:04:43 PM,NaN,NaN,NaN
3,10224740,HY411595,09/05/2015 12:45:00 PM,035XX W BARRY AVE,2023,NARCOTICS,POSS: HEROIN(BRN/TAN),SIDEWALK,True,False,1412,14.00,35.00,21.00,18,"1,152,037.00","1,920,384.00",2015,02/10/2018 03:50:01 PM,41.94,-87.72,"(41.937405765, -87.716649687)"
4,10224741,HY411610,09/05/2015 01:00:00 PM,0000X N LARAMIE AVE,0560,ASSAULT,SIMPLE,APARTMENT,False,True,1522,15.00,28.00,25.00,08A,"1,141,706.00","1,900,086.00",2015,02/10/2018 03:50:01 PM,41.88,-87.76,"(41.881903443, -87.755121152)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7782455,12847575,JF420478,09/01/2022 05:00:00 AM,005XX W SURF ST,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,RESIDENCE,False,True,1934,19.00,44.00,6.00,26,"1,172,497.00","1,919,410.00",2022,01/03/2023 03:46:28 PM,41.93,-87.64,"(41.934304581, -87.641484982)"
7782456,12847801,JF420319,07/08/2022 12:00:00 AM,114XX S PRAIRIE AVE,1130,DECEPTIVE PRACTICE,FRAUD OR CONFIDENCE GAME,STREET,False,False,531,5.00,9.00,49.00,11,"1,179,966.00","1,828,818.00",2022,01/03/2023 03:46:28 PM,41.69,-87.62,"(41.685543881, -87.616812541)"
7782457,12847324,JF420102,09/27/2022 11:00:00 AM,023XX E 70TH ST,0810,THEFT,OVER $500,RESIDENCE,False,False,331,3.00,5.00,43.00,06,"1,193,181.00","1,859,005.00",2022,01/03/2023 03:46:28 PM,41.77,-87.57,"(41.768068052, -87.567452932)"
7782458,12847570,JF420427,09/03/2022 10:25:00 AM,052XX W CARMEN AVE,2021,NARCOTICS,POSSESS - BARBITURATES,RESIDENCE - YARD (FRONT / BACK),True,False,1623,16.00,45.00,11.00,18,"1,140,553.00","1,933,418.00",2022,01/03/2023 03:46:28 PM,41.97,-87.76,"(41.973391184, -87.758534512)"
7782459,12840464,JF411839,09/26/2022 07:20:00 PM,0000X N MASON AVE,143A,WEAPONS VIOLATION,UNLAWFUL POSSESSION - HANDGUN,SIDEWALK,True,False,1513,15.00,29.00,25.00,15,"1,136,773.00","1,899,652.00",2022,01/03/2023 03:46:28 PM,41.88,-87.77,"(41.880802263, -87.773245737)"

In [26]:
# explicitly setting the format to speed up pd.to_datetime
date_format = "%m/%d/%Y %H:%M:%S %p"


### Demonstrating/testing date_format
example = chicago_full.loc[0,'Date']
display(example)
pd.to_datetime(example,format=date_format)

'09/05/2015 01:30:00 PM'

Timestamp('2015-09-05 01:30:00')

In [27]:
# this cell can take up to 1 min to run
chicago_full['Datetime'] = pd.to_datetime(chicago_full['Date'], format=date_format)
chicago_full = chicago_full.sort_values('Datetime')
chicago_full = chicago_full.set_index('Datetime')
chicago_full

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
Datetime,,,,,,,,,,,,,,,,,,,,,,
2001-01-01 01:00:00,1330412,G026686,01/01/2001 01:00:00 AM,019XX N HALSTED ST,0820,THEFT,$500 AND UNDER,TAVERN/LIQUOR STORE,False,False,1813,18.00,NaN,NaN,06,"1,170,604.00","1,913,228.00",2001,08/17/2015 03:03:40 PM,41.92,-87.65,"(41.917382588, -87.648623098)"
2001-01-01 01:00:00,1317937,G001149,01/01/2001 01:00:00 AM,024XX E 73 ST,0460,BATTERY,SIMPLE,RESIDENCE PORCH/HALLWAY,False,False,334,3.00,NaN,NaN,08B,"1,193,629.00","1,856,985.00",2001,08/17/2015 03:03:40 PM,41.76,-87.57,"(41.762514064, -87.565876899)"
2001-01-01 01:00:00,6808288,HR218860,01/01/2001 01:00:00 PM,004XX E OAKWOOD BLVD,0840,THEFT,FINANCIAL ID THEFT: OVER $300,APARTMENT,False,False,213,2.00,3.00,38.00,06,"1,179,872.00","1,878,745.00",2001,05/07/2009 01:05:12 AM,41.82,-87.62,"(41.822551254, -87.615631965)"
2001-01-01 01:00:00,1584605,G351833,01/01/2001 01:00:00 AM,024XX W CORTLAND ST,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,RESIDENCE,False,False,1434,14.00,NaN,NaN,26,"1,159,701.00","1,912,508.00",2001,08/17/2015 03:03:40 PM,41.92,-87.69,"(41.915638736, -87.688700749)"
2001-01-01 01:00:00,5462733,HN290220,01/01/2001 01:00:00 AM,058XX S INDIANA AVE,1752,OFFENSE INVOLVING CHILDREN,AGG CRIM SEX ABUSE FAM MEMBER,RESIDENCE,False,True,233,2.00,20.00,40.00,20,"1,178,551.00","1,866,538.00",2001,04/25/2007 05:57:12 AM,41.79,-87.62,"(41.789084341, -87.620849345)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-04-18 12:50:00,13045687,JG227680,04/18/2023 12:50:00 AM,008XX W FULTON MARKET,0460,BATTERY,SIMPLE,BAR OR TAVERN,False,False,1214,12.00,27.00,28.00,08B,"1,170,577.00","1,902,075.00",2023,04/25/2023 04:47:28 PM,41.89,-87.65,"(41.886778688, -87.649049147)"
2023-04-18 12:51:00,13046438,JG228717,04/18/2023 12:51:00 PM,027XX N LINCOLN AVE,0820,THEFT,$500 AND UNDER,RESIDENCE - PORCH / HALLWAY,False,False,1932,19.00,43.00,7.00,06,"1,168,081.00","1,918,487.00",2023,04/25/2023 04:47:28 PM,41.93,-87.66,"(41.931868465, -87.657740362)"
2023-04-18 12:52:00,13046101,JG228152,04/18/2023 12:52:00 PM,013XX S LAWNDALE AVE,0560,ASSAULT,SIMPLE,STREET,False,False,1011,10.00,24.00,29.00,08A,"1,151,918.00","1,893,645.00",2023,04/25/2023 04:47:28 PM,41.86,-87.72,"(41.864033702, -87.717792133)"
2023-04-18 12:55:00,13046082,JG228160,04/18/2023 12:55:00 PM,009XX W IRVING PARK RD,0860,THEFT,RETAIL THEFT,SMALL RETAIL STORE,False,False,1923,19.00,46.00,6.00,06,"1,169,204.00","1,926,746.00",2023,04/25/2023 04:47:28 PM,41.95,-87.65,"(41.954507152, -87.653372774)"
2023-04-18 12:55:00,13046679,JG227678,04/18/2023 12:55:00 AM,022XX W 47TH PL,1320,CRIMINAL DAMAGE,TO VEHICLE,RESIDENCE,False,False,931,9.00,15.00,61.00,14,"1,161,985.00","1,873,130.00",2023,04/25/2023 04:47:28 PM,41.81,-87.68,"(41.807534292, -87.681408071)"

In [28]:
(chicago_full.isna().sum()/len(chicago_full)).round(2)

ID                     0.00
Case Number            0.00
Date                   0.00
Block                  0.00
IUCR                   0.00
Primary Type           0.00
Description            0.00
Location Description   0.00
Arrest                 0.00
Domestic               0.00
Beat                   0.00
District               0.00
Ward                   0.08
Community Area         0.08
FBI Code               0.00
X Coordinate           0.01
Y Coordinate           0.01
Year                   0.00
Updated On             0.00
Latitude               0.01
Longitude              0.01
Location               0.01
dtype: float64

In [29]:
# save the years for every crime
chicago_full["Year"] = chicago_full.index.year
chicago_full["Year"] = chicago_full["Year"].astype(str)
chicago_full["Year"].value_counts()

2002    486802
2001    485878
2003    475979
2004    469421
2005    453771
2006    448174
2007    437084
2008    427167
2009    392819
2010    370496
2011    351963
2012    336261
2013    307468
2014    275731
2016    269786
2017    269069
2018    268770
2015    264755
2019    261244
2022    238159
2020    212088
2021    208565
2023     71010
Name: Year, dtype: int64

In [30]:
## Dropping unneeded columns to reduce file size
drop_cols = ["X Coordinate","Y Coordinate", "Community Area","FBI Code",
             "Case Number","Updated On",'Block','Location','IUCR']

In [31]:
# save final df
chicago_final = chicago_full.drop(columns=drop_cols).sort_index()#.reset_index()
chicago_final

,ID,Date,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Year,Latitude,Longitude
Datetime,,,,,,,,,,,,,
2001-01-01 01:00:00,1330412,01/01/2001 01:00:00 AM,THEFT,$500 AND UNDER,TAVERN/LIQUOR STORE,False,False,1813,18.00,NaN,2001,41.92,-87.65
2001-01-01 01:00:00,1317937,01/01/2001 01:00:00 AM,BATTERY,SIMPLE,RESIDENCE PORCH/HALLWAY,False,False,334,3.00,NaN,2001,41.76,-87.57
2001-01-01 01:00:00,6808288,01/01/2001 01:00:00 PM,THEFT,FINANCIAL ID THEFT: OVER $300,APARTMENT,False,False,213,2.00,3.00,2001,41.82,-87.62
2001-01-01 01:00:00,1584605,01/01/2001 01:00:00 AM,OTHER OFFENSE,HARASSMENT BY TELEPHONE,RESIDENCE,False,False,1434,14.00,NaN,2001,41.92,-87.69
2001-01-01 01:00:00,5462733,01/01/2001 01:00:00 AM,OFFENSE INVOLVING CHILDREN,AGG CRIM SEX ABUSE FAM MEMBER,RESIDENCE,False,True,233,2.00,20.00,2001,41.79,-87.62
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-04-18 12:50:00,13045687,04/18/2023 12:50:00 AM,BATTERY,SIMPLE,BAR OR TAVERN,False,False,1214,12.00,27.00,2023,41.89,-87.65
2023-04-18 12:51:00,13046438,04/18/2023 12:51:00 PM,THEFT,$500 AND UNDER,RESIDENCE - PORCH / HALLWAY,False,False,1932,19.00,43.00,2023,41.93,-87.66
2023-04-18 12:52:00,13046101,04/18/2023 12:52:00 PM,ASSAULT,SIMPLE,STREET,False,False,1011,10.00,24.00,2023,41.86,-87.72
2023-04-18 12:55:00,13046082,04/18/2023 12:55:00 PM,THEFT,RETAIL THEFT,SMALL RETAIL STORE,False,False,1923,19.00,46.00,2023,41.95,-87.65
2023-04-18 12:55:00,13046679,04/18/2023 12:55:00 AM,CRIMINAL DAMAGE,TO VEHICLE,RESIDENCE,False,False,931,9.00,15.00,2023,41.81,-87.68

In [32]:
chicago_final.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 7782460 entries, 2001-01-01 01:00:00 to 2023-04-18 12:55:00
Data columns (total 13 columns):
 #   Column                Dtype
---  ------                -----
 0   ID                    int64
 1   Date                  object
 2   Primary Type          object
 3   Description           object
 4   Location Description  object
 5   Arrest                bool
 6   Domestic              bool
 7   Beat                  int64
 8   District              float64
 9   Ward                  float64
 10  Year                  object
 11  Latitude              float64
 12  Longitude             float64
dtypes: bool(2), float64(4), int64(2), object(5)
memory usage: 727.3+ MB

In [33]:
chicago_final.memory_usage(deep=True).astype(float)

Index                   62,259,680.00
ID                      62,259,680.00
Date                   614,814,340.00
Primary Type           521,706,205.00
Description            569,620,353.00
Location Description   530,448,494.00
Arrest                   7,782,460.00
Domestic                 7,782,460.00
Beat                    62,259,680.00
District                62,259,680.00
Ward                    62,259,680.00
Year                   474,730,060.00
Latitude                62,259,680.00
Longitude               62,259,680.00
dtype: float64

In [34]:
# unique # of year bins
year_bins = chicago_final['Year'].astype(str).unique()
year_bins

array(['2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008',
       '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016',
       '2017', '2018', '2019', '2020', '2021', '2022', '2023'],
      dtype=object)

In [35]:
FINAL_DROP = ['Datetime','Year']#,'Location Description']

In [36]:
## set save location 

os.makedirs(OUTPUT_FOLDER, exist_ok=True)
print(f"[i] Saving .csv's to {OUTPUT_FOLDER}")
## loop through years
for year in year_bins:
    
    ## save temp slices of dfs to save.
    temp_df = chicago_final.loc[ year]
    temp_df = temp_df.reset_index(drop=False)
    temp_df = temp_df.drop(columns=FINAL_DROP)

    # save as csv to output folder
    fname_temp = f"{OUTPUT_FOLDER}Chicago-Crime_{year}.csv"#.gz
    temp_df.to_csv(fname_temp,index=False)

    print(f"- Succesfully saved {fname_temp}")

[i] Saving .csv's to Data/Chicago/
- Succesfully saved Data/Chicago/Chicago-Crime_2001.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2002.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2003.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2004.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2005.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2006.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2007.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2008.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2009.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2010.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2011.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2012.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2013.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2014.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2015.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2016.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2017.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2018.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2019.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2020.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2021.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2022.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2023.csv

In [37]:
saved_files = sorted(glob.glob(OUTPUT_FOLDER+'*.*csv'))
saved_files

['Data/Chicago/Chicago-Crime_2001.csv',
 'Data/Chicago/Chicago-Crime_2002.csv',
 'Data/Chicago/Chicago-Crime_2003.csv',
 'Data/Chicago/Chicago-Crime_2004.csv',
 'Data/Chicago/Chicago-Crime_2005.csv',
 'Data/Chicago/Chicago-Crime_2006.csv',
 'Data/Chicago/Chicago-Crime_2007.csv',
 'Data/Chicago/Chicago-Crime_2008.csv',
 'Data/Chicago/Chicago-Crime_2009.csv',
 'Data/Chicago/Chicago-Crime_2010.csv',
 'Data/Chicago/Chicago-Crime_2011.csv',
 'Data/Chicago/Chicago-Crime_2012.csv',
 'Data/Chicago/Chicago-Crime_2013.csv',
 'Data/Chicago/Chicago-Crime_2014.csv',
 'Data/Chicago/Chicago-Crime_2015.csv',
 'Data/Chicago/Chicago-Crime_2016.csv',
 'Data/Chicago/Chicago-Crime_2017.csv',
 'Data/Chicago/Chicago-Crime_2018.csv',
 'Data/Chicago/Chicago-Crime_2019.csv',
 'Data/Chicago/Chicago-Crime_2020.csv',
 'Data/Chicago/Chicago-Crime_2021.csv',
 'Data/Chicago/Chicago-Crime_2022.csv',
 'Data/Chicago/Chicago-Crime_2023.csv']

In [38]:
## create a README.txt for the zip files
readme = """Source URL: 
- https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-Present/ijzp-q8t2
- Filtered for years 2000-Present.

Downloaded 07/18/2022
- Files are split into 1 year per file.

EXAMPLE USAGE:
>> import glob
>> import pandas as pd
>> folder = "Data/Chicago/"
>> crime_files = sorted(glob.glob(folder+"*.csv"))
>> df = pd.concat([pd.read_csv(f) for f in crime_files])
"""
print(readme)


with open(f"{OUTPUT_FOLDER}README.txt",'w') as f:
    f.write(readme)

Source URL:
- https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-Present/ijzp-q8t2
- Filtered for years 2000-Present.

Downloaded 07/18/2022
- Files are split into 1 year per file.

EXAMPLE USAGE:
>> import glob
>> import pandas as pd
>> folder = "Data/Chicago/"
>> crime_files = sorted(glob.glob(folder+"*.csv"))
>> df = pd.concat([pd.read_csv(f) for f in crime_files])

In [39]:
# get list of files from folder
crime_files = sorted(glob.glob(OUTPUT_FOLDER+"*.csv"))
df = pd.concat([pd.read_csv(f) for f in crime_files])
df

,ID,Date,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Latitude,Longitude
0,1330412,01/01/2001 01:00:00 AM,THEFT,$500 AND UNDER,TAVERN/LIQUOR STORE,False,False,1813,18.00,NaN,41.92,-87.65
1,1317937,01/01/2001 01:00:00 AM,BATTERY,SIMPLE,RESIDENCE PORCH/HALLWAY,False,False,334,3.00,NaN,41.76,-87.57
2,6808288,01/01/2001 01:00:00 PM,THEFT,FINANCIAL ID THEFT: OVER $300,APARTMENT,False,False,213,2.00,3.00,41.82,-87.62
3,1584605,01/01/2001 01:00:00 AM,OTHER OFFENSE,HARASSMENT BY TELEPHONE,RESIDENCE,False,False,1434,14.00,NaN,41.92,-87.69
4,5462733,01/01/2001 01:00:00 AM,OFFENSE INVOLVING CHILDREN,AGG CRIM SEX ABUSE FAM MEMBER,RESIDENCE,False,True,233,2.00,20.00,41.79,-87.62
...,...,...,...,...,...,...,...,...,...,...,...,...
71005,13045687,04/18/2023 12:50:00 AM,BATTERY,SIMPLE,BAR OR TAVERN,False,False,1214,12.00,27.00,41.89,-87.65
71006,13046438,04/18/2023 12:51:00 PM,THEFT,$500 AND UNDER,RESIDENCE - PORCH / HALLWAY,False,False,1932,19.00,43.00,41.93,-87.66
71007,13046101,04/18/2023 12:52:00 PM,ASSAULT,SIMPLE,STREET,False,False,1011,10.00,24.00,41.86,-87.72
71008,13046082,04/18/2023 12:55:00 PM,THEFT,RETAIL THEFT,SMALL RETAIL STORE,False,False,1923,19.00,46.00,41.95,-87.65
71009,13046679,04/18/2023 12:55:00 AM,CRIMINAL DAMAGE,TO VEHICLE,RESIDENCE,False,False,931,9.00,15.00,41.81,-87.68

In [40]:
years = df['Date'].map(lambda x: x.split()[0].split('/')[-1])
years.value_counts().sort_index()

2001    485878
2002    486802
2003    475979
2004    469421
2005    453771
2006    448174
2007    437084
2008    427167
2009    392819
2010    370496
2011    351963
2012    336261
2013    307468
2014    275731
2015    264755
2016    269786
2017    269069
2018    268770
2019    261244
2020    212088
2021    208565
2022    238159
2023     71010
Name: Date, dtype: int64